# -*- coding: utf-8 -*-
"""TrianglePattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15i6RuNOUFUv_-OC-DStKUvrHTGvyuRrT

### **Lower Triangular Pattern**
"""

n = 5

for i in range(1, n + 1):
    print("* " * i)

"""### **Upper Triangular Pattern**"""

n = 5

for i in range(n, 0, -1):
    print("* " * i)

"""### **Pyramid Pattern**"""

n = 5

for i in range(n):
    print(" " * (n - i - 1) + "* " * (i + 1))